name: cupertino_controllers
description: A Flutter plugin with Cupertino Controller Examples. This includes a Table View Controller, Master Detail Controller, Cupertino Cell with Xcode Storyboard templates (basic detail, subtitle...), and detail examples
version: 0.1.1
author: Rhodes Davis Jr. <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins/tree/master/packages/cupertino_controllers

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^0.5.3
  flutter_sticky_header: ^0.4.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
